version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always  

  api-node:
    build:
      context: ./api-node
    container_name: api-node-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql 
    environment:
      DB_HOST: mysql
      DB_USER: usuario
      DB_PASSWORD: senha
      DB_DATABASE: teste_db
    restart: always  

  frontend-php:
    build:
      context: ./frontend-php
    container_name: frontend-php-container
    ports:
      - "8080:80"
    depends_on:
      - api-node  
    restart: always  